FROM confluentinc/cp-kafka-connect:7.6.0

USER root

# Bypass Confluent Hub and directly download the Java 11 compatible Debezium 2.5.0 plugin
RUN mkdir -p /usr/share/confluent-hub-components/debezium-connector-postgresql && \
    curl -L https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.5.0.Final/debezium-connector-postgres-2.5.0.Final-plugin.tar.gz \
    | tar -xz -C /usr/share/confluent-hub-components/debezium-connector-postgresql --strip-components=1

USER appuser
